// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: VariousArgsAndReturnsRPCExample.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

public static partial class RPCExample
{
  static readonly string __ServiceName = "RPCExample";

  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
  {
    #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
    if (message is global::Google.Protobuf.IBufferMessage)
    {
      context.SetPayloadLength(message.CalculateSize());
      global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
      context.Complete();
      return;
    }
    #endif
    context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
  }

  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static class __Helper_MessageCache<T>
  {
    public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
  }

  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
  {
    #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
    if (__Helper_MessageCache<T>.IsBufferMessage)
    {
      return parser.ParseFrom(context.PayloadAsReadOnlySequence());
    }
    #endif
    return parser.ParseFrom(context.PayloadAsNewBuffer());
  }

  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static readonly grpc::Marshaller<global::ExampleOneArgOneReturnRequest> __Marshaller_ExampleOneArgOneReturnRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ExampleOneArgOneReturnRequest.Parser));
  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static readonly grpc::Marshaller<global::ExampleOneArgOneReturnResponse> __Marshaller_ExampleOneArgOneReturnResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ExampleOneArgOneReturnResponse.Parser));
  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static readonly grpc::Marshaller<global::TestRPCNoArgsResponse> __Marshaller_TestRPCNoArgsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::TestRPCNoArgsResponse.Parser));
  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static readonly grpc::Marshaller<global::TestRPCNoReturnRequest> __Marshaller_TestRPCNoReturnRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::TestRPCNoReturnRequest.Parser));
  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static readonly grpc::Marshaller<global::TestRPCTwoArgTwoReturnRequest> __Marshaller_TestRPCTwoArgTwoReturnRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::TestRPCTwoArgTwoReturnRequest.Parser));
  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static readonly grpc::Marshaller<global::TestRPCTwoArgTwoReturnResponse> __Marshaller_TestRPCTwoArgTwoReturnResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::TestRPCTwoArgTwoReturnResponse.Parser));

  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static readonly grpc::Method<global::ExampleOneArgOneReturnRequest, global::ExampleOneArgOneReturnResponse> __Method_ExampleOneArgOneReturn = new grpc::Method<global::ExampleOneArgOneReturnRequest, global::ExampleOneArgOneReturnResponse>(
      grpc::MethodType.Unary,
      __ServiceName,
      "ExampleOneArgOneReturn",
      __Marshaller_ExampleOneArgOneReturnRequest,
      __Marshaller_ExampleOneArgOneReturnResponse);

  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::TestRPCNoArgsResponse> __Method_TestRPCNoArgs = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::TestRPCNoArgsResponse>(
      grpc::MethodType.Unary,
      __ServiceName,
      "TestRPCNoArgs",
      __Marshaller_google_protobuf_Empty,
      __Marshaller_TestRPCNoArgsResponse);

  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty> __Method_TestRPCNoInputNoReturn = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(
      grpc::MethodType.Unary,
      __ServiceName,
      "TestRPCNoInputNoReturn",
      __Marshaller_google_protobuf_Empty,
      __Marshaller_google_protobuf_Empty);

  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static readonly grpc::Method<global::TestRPCNoReturnRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_TestRPCNoReturn = new grpc::Method<global::TestRPCNoReturnRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
      grpc::MethodType.Unary,
      __ServiceName,
      "TestRPCNoReturn",
      __Marshaller_TestRPCNoReturnRequest,
      __Marshaller_google_protobuf_Empty);

  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  static readonly grpc::Method<global::TestRPCTwoArgTwoReturnRequest, global::TestRPCTwoArgTwoReturnResponse> __Method_TestRPCTwoArgTwoReturn = new grpc::Method<global::TestRPCTwoArgTwoReturnRequest, global::TestRPCTwoArgTwoReturnResponse>(
      grpc::MethodType.Unary,
      __ServiceName,
      "TestRPCTwoArgTwoReturn",
      __Marshaller_TestRPCTwoArgTwoReturnRequest,
      __Marshaller_TestRPCTwoArgTwoReturnResponse);

  /// <summary>Service descriptor</summary>
  public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
  {
    get { return global::VariousArgsAndReturnsRPCExampleReflection.Descriptor.Services[0]; }
  }

  /// <summary>Base class for server-side implementations of RPCExample</summary>
  [grpc::BindServiceMethod(typeof(RPCExample), "BindService")]
  public abstract partial class RPCExampleBase
  {
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::System.Threading.Tasks.Task<global::ExampleOneArgOneReturnResponse> ExampleOneArgOneReturn(global::ExampleOneArgOneReturnRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::System.Threading.Tasks.Task<global::TestRPCNoArgsResponse> TestRPCNoArgs(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> TestRPCNoInputNoReturn(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> TestRPCNoReturn(global::TestRPCNoReturnRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::System.Threading.Tasks.Task<global::TestRPCTwoArgTwoReturnResponse> TestRPCTwoArgTwoReturn(global::TestRPCTwoArgTwoReturnRequest request, grpc::ServerCallContext context)
    {
      throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
    }

  }

  /// <summary>Client for RPCExample</summary>
  public partial class RPCExampleClient : grpc::ClientBase<RPCExampleClient>
  {
    /// <summary>Creates a new client for RPCExample</summary>
    /// <param name="channel">The channel to use to make remote calls.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public RPCExampleClient(grpc::ChannelBase channel) : base(channel)
    {
    }
    /// <summary>Creates a new client for RPCExample that uses a custom <c>CallInvoker</c>.</summary>
    /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public RPCExampleClient(grpc::CallInvoker callInvoker) : base(callInvoker)
    {
    }
    /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    protected RPCExampleClient() : base()
    {
    }
    /// <summary>Protected constructor to allow creation of configured clients.</summary>
    /// <param name="configuration">The client configuration.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    protected RPCExampleClient(ClientBaseConfiguration configuration) : base(configuration)
    {
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::ExampleOneArgOneReturnResponse ExampleOneArgOneReturn(global::ExampleOneArgOneReturnRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ExampleOneArgOneReturn(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::ExampleOneArgOneReturnResponse ExampleOneArgOneReturn(global::ExampleOneArgOneReturnRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_ExampleOneArgOneReturn, null, options, request);
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual grpc::AsyncUnaryCall<global::ExampleOneArgOneReturnResponse> ExampleOneArgOneReturnAsync(global::ExampleOneArgOneReturnRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return ExampleOneArgOneReturnAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual grpc::AsyncUnaryCall<global::ExampleOneArgOneReturnResponse> ExampleOneArgOneReturnAsync(global::ExampleOneArgOneReturnRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_ExampleOneArgOneReturn, null, options, request);
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::TestRPCNoArgsResponse TestRPCNoArgs(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return TestRPCNoArgs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::TestRPCNoArgsResponse TestRPCNoArgs(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_TestRPCNoArgs, null, options, request);
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual grpc::AsyncUnaryCall<global::TestRPCNoArgsResponse> TestRPCNoArgsAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return TestRPCNoArgsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual grpc::AsyncUnaryCall<global::TestRPCNoArgsResponse> TestRPCNoArgsAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_TestRPCNoArgs, null, options, request);
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::Google.Protobuf.WellKnownTypes.Empty TestRPCNoInputNoReturn(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return TestRPCNoInputNoReturn(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::Google.Protobuf.WellKnownTypes.Empty TestRPCNoInputNoReturn(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_TestRPCNoInputNoReturn, null, options, request);
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> TestRPCNoInputNoReturnAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return TestRPCNoInputNoReturnAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> TestRPCNoInputNoReturnAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_TestRPCNoInputNoReturn, null, options, request);
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::Google.Protobuf.WellKnownTypes.Empty TestRPCNoReturn(global::TestRPCNoReturnRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return TestRPCNoReturn(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::Google.Protobuf.WellKnownTypes.Empty TestRPCNoReturn(global::TestRPCNoReturnRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_TestRPCNoReturn, null, options, request);
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> TestRPCNoReturnAsync(global::TestRPCNoReturnRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return TestRPCNoReturnAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> TestRPCNoReturnAsync(global::TestRPCNoReturnRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_TestRPCNoReturn, null, options, request);
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::TestRPCTwoArgTwoReturnResponse TestRPCTwoArgTwoReturn(global::TestRPCTwoArgTwoReturnRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return TestRPCTwoArgTwoReturn(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual global::TestRPCTwoArgTwoReturnResponse TestRPCTwoArgTwoReturn(global::TestRPCTwoArgTwoReturnRequest request, grpc::CallOptions options)
    {
      return CallInvoker.BlockingUnaryCall(__Method_TestRPCTwoArgTwoReturn, null, options, request);
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual grpc::AsyncUnaryCall<global::TestRPCTwoArgTwoReturnResponse> TestRPCTwoArgTwoReturnAsync(global::TestRPCTwoArgTwoReturnRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
    {
      return TestRPCTwoArgTwoReturnAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
    }
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public virtual grpc::AsyncUnaryCall<global::TestRPCTwoArgTwoReturnResponse> TestRPCTwoArgTwoReturnAsync(global::TestRPCTwoArgTwoReturnRequest request, grpc::CallOptions options)
    {
      return CallInvoker.AsyncUnaryCall(__Method_TestRPCTwoArgTwoReturn, null, options, request);
    }
    /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    protected override RPCExampleClient NewInstance(ClientBaseConfiguration configuration)
    {
      return new RPCExampleClient(configuration);
    }
  }

  /// <summary>Creates service definition that can be registered with a server</summary>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  public static grpc::ServerServiceDefinition BindService(RPCExampleBase serviceImpl)
  {
    return grpc::ServerServiceDefinition.CreateBuilder()
        .AddMethod(__Method_ExampleOneArgOneReturn, serviceImpl.ExampleOneArgOneReturn)
        .AddMethod(__Method_TestRPCNoArgs, serviceImpl.TestRPCNoArgs)
        .AddMethod(__Method_TestRPCNoInputNoReturn, serviceImpl.TestRPCNoInputNoReturn)
        .AddMethod(__Method_TestRPCNoReturn, serviceImpl.TestRPCNoReturn)
        .AddMethod(__Method_TestRPCTwoArgTwoReturn, serviceImpl.TestRPCTwoArgTwoReturn).Build();
  }

  /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
  /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
  /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
  /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
  [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
  public static void BindService(grpc::ServiceBinderBase serviceBinder, RPCExampleBase serviceImpl)
  {
    serviceBinder.AddMethod(__Method_ExampleOneArgOneReturn, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ExampleOneArgOneReturnRequest, global::ExampleOneArgOneReturnResponse>(serviceImpl.ExampleOneArgOneReturn));
    serviceBinder.AddMethod(__Method_TestRPCNoArgs, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::TestRPCNoArgsResponse>(serviceImpl.TestRPCNoArgs));
    serviceBinder.AddMethod(__Method_TestRPCNoInputNoReturn, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Google.Protobuf.WellKnownTypes.Empty, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.TestRPCNoInputNoReturn));
    serviceBinder.AddMethod(__Method_TestRPCNoReturn, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::TestRPCNoReturnRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.TestRPCNoReturn));
    serviceBinder.AddMethod(__Method_TestRPCTwoArgTwoReturn, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::TestRPCTwoArgTwoReturnRequest, global::TestRPCTwoArgTwoReturnResponse>(serviceImpl.TestRPCTwoArgTwoReturn));
  }

}
#endregion
